"""
Database Schemas

Define your MongoDB collection schemas here using Pydantic models.
These schemas are used for data validation in your application.

Each Pydantic model represents a collection in your database.
Model name is converted to lowercase for the collection name:
- User -> "user" collection
- Product -> "product" collection
- BlogPost -> "blogs" collection
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

# Example schemas (retain examples for reference)

class User(BaseModel):
    """
    Users collection schema
    Collection name: "user" (lowercase of class name)
    """
    name: str = Field(..., description="Full name")
    email: str = Field(..., description="Email address")
    address: str = Field(..., description="Address")
    age: Optional[int] = Field(None, ge=0, le=120, description="Age in years")
    is_active: bool = Field(True, description="Whether user is active")

class Product(BaseModel):
    """
    Products collection schema
    Collection name: "product" (lowercase of class name)
    """
    title: str = Field(..., description="Product title")
    description: Optional[str] = Field(None, description="Product description")
    price: float = Field(..., ge=0, description="Price in dollars")
    category: str = Field(..., description="Product category")
    in_stock: bool = Field(True, description="Whether product is in stock")

# Code Review specific schemas

class Finding(BaseModel):
    type: str = Field(..., description="Category: bug, performance, quality, security")
    severity: str = Field(..., description="low, medium, high, critical")
    message: str
    line: Optional[int] = Field(None, description="Line number if available")
    snippet: Optional[str] = None

class CodeReview(BaseModel):
    """
    Code reviews collection schema
    Collection name: "codereview"
    """
    filename: str = Field(..., description="Original filename")
    language: Optional[str] = Field(None, description="Programming language")
    original_code: str = Field(..., description="Original source code")
    optimized_code: Optional[str] = Field(None, description="Optimized code generated by the analyzer")
    diff: Optional[str] = Field(None, description="Unified diff between original and optimized code")
    findings: List[Finding] = Field(default_factory=list, description="List of issues and suggestions")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Code metrics like lines, complexity estimate")
    summary: Optional[str] = Field(None, description="High-level summary of feedback")
